/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Alerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Auth": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "AuthAuthenticator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "AuthRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AutodeployConfig": {
      "buildImage": string
      "buildspecBucketName": string
      "buildspecVersion": string
      "configParserFunctionArn": string
      "runnerRemoverFunctionArn": string
      "runnerRemoverScheduleGroupName": string
      "runnerRemoverScheduleRoleArn": string
      "timeoutMonitorFunctionArn": string
      "timeoutMonitorScheduleGroupName": string
      "timeoutMonitorScheduleRoleArn": string
      "type": "sst.sst.Linkable"
    }
    "AutodeployConfigParser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AutodeployRunnerRemover": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AutodeployTimeoutMonitor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BillingQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BotpoisonSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Connect": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Error": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "GithubAppID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IssueDestination": {
      "cfn": string
      "prefix": string
      "role": string
      "stream": string
      "type": "sst.sst.Linkable"
    }
    "IssueDetectionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "IssueLambda": {
      "name": string
      "type": "sst.aws.Function"
    }
    "IssueStream": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "SlackClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StripeInvocationsPriceID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeResourcesPriceID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VPC": {
      "type": "sst.aws.Vpc"
    }
    "Websocket": {
      "http": string
      "realtime": string
      "token": string
      "type": "sst.sst.Linkable"
    }
    "WebsocketAuthorizer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WebsocketToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Workspace": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}