/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Alerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "Api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Auth": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "AuthAuthenticator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "BotpoisonSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Connect": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Error": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "GithubAppID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IssueDestination": {
      "prefix": string
      "role": string
      "stream": string
      "type": "sst.sst.Linkable"
    }
    "IssueStream": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "SlackClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "workspace": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
