/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Alerts": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "Auth": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "BotpoisonSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "GithubAppID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IssueDestination": {
      "prefix": string
      "role": string
      "stream": string
      "type": "sst.sst.Linkable"
    }
    "IssueStream": {
      "name": string
      "type": "sst.aws.KinesisStream"
    }
    "SlackClientID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Websocket": {
      "http": string
      "realtime": string
      "token": string
      "type": "sst.sst.Linkable"
    }
    "WebsocketToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
